import { app, BrowserWindow, ipcMain, desktopCapturer, screen, session, dialog, nativeImage, shell, globalShortcut, protocol, Tray, Menu, Notification } from 'electron';
import * as path from 'path';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import Store from 'electron-store';
import { exec } from 'child_process';
import { promisify } from 'util';
import type { Result as ActiveWindowResult } from 'active-win';
import { Settings, KeyboardShortcut } from './types';
import * as activeWin from 'active-win';
import { supabase } from './utils/supabase';
import type { Session } from '@supabase/supabase-js';

const execAsync = promisify(exec);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Load environment variables
const envPath = path.join(__dirname, '..', '..', '.env');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const isDevelopment = process.env.NODE_ENV !== 'production';

let tray: Tray | null = null;
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // If window already exists, just show it
  if (mainWindow) {
    mainWindow.show();
    return;
  }

  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
    },
    backgroundColor: '#000000',
    darkTheme: true,
    skipTaskbar: false,
    show: false, // Don't show until ready-to-show
  });

  // Show window when ready
  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  // Handle window state
  mainWindow.on('close', function(e: Electron.Event) {
    if (!app.isQuitting) {
      e.preventDefault();
      mainWindow?.hide();
    }
  });

  // Handle window state changes
  mainWindow.on('show', () => {
    if (tray) {
      tray.setToolTip('Quvox (Running)');
    }
  });

  mainWindow.on('hide', () => {
    if (tray) {
      tray.setToolTip('Quvox (Hidden)');
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools if debug mode is enabled.
  if (process.env.ENABLE_DEBUG_MODE === 'true') {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Set app name for notifications
  if (process.platform === 'win32') {
    app.setAppUserModelId('Quvox');
  }
  createWindow();
});

// Create tray icon
const createTray = () => {
  // Create empty tray icon as fallback
  tray = new Tray(nativeImage.createEmpty());

  // Try to create proper icon
  const iconPath = path.join(__dirname, '..', 'assets', 'icon.png');
  if (fs.existsSync(iconPath)) {
    const trayIcon = nativeImage.createFromPath(iconPath);
    tray.setImage(trayIcon);
  }

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Show/Hide App',
      click: () => {
        if (mainWindow?.isVisible()) {
          mainWindow.hide();
        } else {
          mainWindow?.show();
          mainWindow?.focus();
        }
      }
    },
    {
      type: 'separator'
    },
    {
      label: 'Exit',
      click: () => {
        app.isQuitting = true;
        app.quit();
      }
    }
  ]);

  tray.setToolTip('Quvox');
  tray.setContextMenu(contextMenu);

  tray.on('click', () => {
    if (mainWindow?.isVisible()) {
      mainWindow.hide();
    } else {
      mainWindow?.show();
      mainWindow?.focus();
    }
  });
};

// Set up Content Security Policy
const setupCSP = () => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    if (!supabaseUrl) {
      console.error('SUPABASE_URL environment variable is not set');
      app.quit();
      return;
    }

    // Extract the hostname from the Supabase URL
    const supabaseHostname = new URL(supabaseUrl).hostname;

    // Define CSP directives based on environment
    const scriptSrcDirectives = isDevelopment
      ? "'self' 'unsafe-eval' 'unsafe-inline'"
      : "'self'";

    const connectSrcDirectives = isDevelopment
      ? `'self' https://${supabaseHostname} wss://${supabaseHostname} ws://localhost:3000 http://localhost:3000`
      : `'self' https://${supabaseHostname} wss://${supabaseHostname}`;

    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          `default-src 'self' https://${supabaseHostname};`,
          `script-src ${scriptSrcDirectives};`,
          "style-src 'self' 'unsafe-inline';",
          "img-src 'self' data: blob: file:;",
          `connect-src ${connectSrcDirectives};`,
          "font-src 'self';"
        ].join(' ')
      }
    });
  });
};

// Update app initialization to include CSP setup
app.whenReady().then(() => {
  setupCSP();
  createWindow();
  createTray();
  registerGlobalShortcut();
  
  // Initialize launch on startup setting
  const settings = store.store;
  app.setLoginItemSettings({
    openAtLogin: settings.launchOnStartup,
    path: app.getPath('exe')
  });
});

// Handle notifications properly
const showNotification = (title: string, body: string, icon?: Electron.NativeImage, screenshotPath?: string) => {
  // Create notification config
  const notificationConfig = {
    title: `Quvox - ${title}`,
    body,
    icon,
    silent: false,
    screenshotPath
  };

  // If window is visible and focused, send event to renderer
  if (mainWindow?.isVisible() && mainWindow?.isFocused()) {
    mainWindow.webContents.send('show-notification', notificationConfig);
  } else {
    // Use native notification if window is minimized or unfocused
    const notification = new Notification(notificationConfig);
    notification.show();
    
    // Open the screenshot when notification is clicked
    notification.on('click', async () => {
      if (screenshotPath) {
        try {
          await shell.openPath(screenshotPath);
        } catch (error) {
          console.error('Error opening screenshot:', error);
          mainWindow?.show();
        }
      } else {
        mainWindow?.show();
      }
    });
  }
};

// Update screenshot save handler
async function handleScreenshotSave(event: any, { screenshot, savePath, metaPath, metadata }: { screenshot: string; savePath: string; metaPath: string; metadata: any }) {
  try {
    // Save the screenshot
    const screenshotBuffer = Buffer.from(screenshot, 'base64');
    await fs.promises.writeFile(savePath, screenshotBuffer);
    
    // Save the metadata
    if (metaPath) {
      await fs.promises.writeFile(metaPath, JSON.stringify(metadata, null, 2));
    }
    
    // Create screenshot data with consistent metadata
    const screenshotData = {
      id: metadata?.id || path.basename(savePath, '.png'),
      timestamp: metadata?.timestamp || Date.now(),
      path: savePath,
      name: path.basename(savePath),
      thumbnail: screenshot,
      metadata: {
        ...metadata,
        source: metadata?.source || 'manual',
        category: metadata?.category || 'uncategorized',
        activeWindow: metadata?.activeWindow || undefined
      }
    };

    // Send screenshot:captured event to renderer and show notification
    if (store.store.showNotifications) {
      // Create a native image from the screenshot buffer for the notification
      const notificationIcon = nativeImage.createFromBuffer(screenshotBuffer);
      
      // Resize the icon to a reasonable size for the notification (e.g., 256x256)
      const size = notificationIcon.getSize();
      const scaleFactor = 256 / Math.max(size.width, size.height);
      const resizedIcon = notificationIcon.resize({
        width: Math.round(size.width * scaleFactor),
        height: Math.round(size.height * scaleFactor),
        quality: 'good'
      });

      const notificationMessage = metadata?.activeWindow?.app 
        ? `Screenshot taken from ${metadata.activeWindow.app}`
        : 'Screenshot captured';

      showNotification(
        'Screenshot Captured',
        notificationMessage,
        resizedIcon,
        savePath
      );
    }

    // Always send the event to renderer for state updates
    mainWindow?.webContents.send('screenshot:captured', screenshotData);

    return screenshotData;
  } catch (error) {
    console.error('Error saving screenshot:', error);
    return false;
  }
}

// Add isQuitting flag to app
declare global {
  namespace Electron {
    interface App {
      isQuitting: boolean;
    }
  }
}

app.isQuitting = false;

// Update quit handling
app.on('before-quit', () => {
  app.isQuitting = true;
});

// Handle window-all-closed
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.isQuitting = true;
    app.quit();
  }
});

// Handle activate
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  } else {
    mainWindow?.show();
  }
});

// Handle screenshot capture request
ipcMain.handle('screenshot:capture', async (event, options) => {
  try {
    const { displayId } = options;
    const primaryDisplay = screen.getPrimaryDisplay();
    const { width, height } = primaryDisplay.bounds;

    const sources = await desktopCapturer.getSources({
      types: ['screen'],
      thumbnailSize: { width, height }
    });

    const source = displayId
      ? sources.find(s => s.display_id === displayId)
      : sources[0];

    if (!source || !source.thumbnail) {
      throw new Error('Failed to capture screenshot');
    }

    // Get active window information
    const activeWindow = await activeWin.activeWindow();

    // Create screenshot data
    const timestamp = Date.now();
    const id = `screenshot_${timestamp}`;
    const screenshotBuffer = source.thumbnail.toPNG();
    const base64Data = screenshotBuffer.toString('base64');

    // Create metadata
    const metadata = {
      id,
      timestamp,
      source: 'button',
      category: 'manual',
      activeWindow: activeWindow ? {
        title: activeWindow.title,
        app: activeWindow.owner.name,
        path: activeWindow.owner.path
      } : undefined
    };

    // Get storage path from settings
    const savePath = path.join(store.store.storagePath, `${id}.png`);
    const metaPath = savePath.replace('.png', '.json');

    // Save the screenshot and metadata
    const screenshotData = await handleScreenshotSave(event, {
      screenshot: base64Data,
      savePath,
      metaPath,
      metadata
    });

    return base64Data;
  } catch (error) {
    console.error('Error capturing screenshot:', error);
    return null;
  }
});

// Handle screenshot save request
ipcMain.handle('screenshot:save', async (event, data) => {
  const screenshotData = await handleScreenshotSave(event, data);
  return screenshotData;
});

// Handle auto-capture start
ipcMain.handle('start-auto-capture', async (event, selectedApps: string[]) => {
  try {
    // Store the selected apps in settings
    store.set('selectedApps', selectedApps);

    // Get active window information
    const activeWindowInfo = await activeWin.activeWindow();

    // Return success even if we don't capture immediately
    // The renderer will handle the interval-based captures
    return {
      success: true,
      activeWindow: activeWindowInfo ? {
        title: activeWindowInfo.title,
        app: activeWindowInfo.owner.name,
        path: activeWindowInfo.owner.path
      } : null
    };
  } catch (error) {
    console.error('Error in auto capture:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    };
  }
});

// Handle auto-capture stop
ipcMain.handle('stop-auto-capture', async () => {
  try {
    return true;
  } catch (error) {
    console.error('Error stopping auto capture:', error);
    return false;
  }
});

// Handle getting app data path
ipcMain.handle('get-app-data-path', () => {
  return app.getPath('userData');
});

// Handle directory creation
ipcMain.handle('ensure-dir', (event, { dirPath }) => {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
  return dirPath;
});

// Initialize settings store
const store = new Store<Settings>({
  defaults: {
    captureInterval: 5,
    launchOnStartup: false,
    showNotifications: true,
    selectedApps: [],
    shortcut: {
      key: 'P',
      ctrl: true,
      shift: true,
      alt: false
    },
    storagePath: path.join(app.getPath('userData'), 'screenshots')
  }
});

// Ensure screenshot directory exists
const screenshotDir = store.get('storagePath');
if (!fs.existsSync(screenshotDir)) {
  fs.mkdirSync(screenshotDir, { recursive: true });
}

// Handle getting available apps
ipcMain.handle('get-available-apps', async () => {
  try {
    let apps: { name: string; icon?: string; isActive: boolean }[] = [];

    if (process.platform === 'win32') {
      // Get running apps on Windows using PowerShell
      const { stdout } = await execAsync('powershell "Get-Process | Where-Object {$_.MainWindowTitle} | Select-Object ProcessName"');
      apps = stdout.split('\n')
        .filter(line => line.trim() && !line.includes('ProcessName'))
        .map(line => ({
          name: line.trim(),
          isActive: true,
        }));
    } else if (process.platform === 'darwin') {
      // Get running apps on macOS
      const { stdout } = await execAsync('ps -axo comm=');
      apps = stdout.split('\n')
        .filter(line => line.trim() && !line.includes('ps'))
        .map(line => ({
          name: path.basename(line.trim(), '.app'),
          isActive: true,
        }));
    }

    return apps;
  } catch (error) {
    console.error('Error getting available apps:', error);
    return [];
  }
});

// Handle loading settings
ipcMain.handle('load-settings', () => {
  return store.store;
});

// Handle saving settings
ipcMain.handle('save-settings', (event, newSettings: Partial<Settings>) => {
  const currentSettings = store.store;
  store.store = { ...currentSettings, ...newSettings };
  
  // Handle launch on startup setting
  if (newSettings.hasOwnProperty('launchOnStartup')) {
    app.setLoginItemSettings({
      openAtLogin: newSettings.launchOnStartup,
      path: app.getPath('exe')
    });
  }
  
  if (newSettings.shortcut) {
    registerGlobalShortcut();
  }
  return true;
});

// Handle selecting directory
ipcMain.handle('select-directory', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
  });

  if (!result.canceled && result.filePaths.length > 0) {
    return result.filePaths[0];
  }
  return null;
});

// Handle updating storage path
ipcMain.handle('update-storage-path', async (event, newPath: string) => {
  const oldPath = store.store.storagePath;
  
  // Create new directory if it doesn't exist
  if (!fs.existsSync(newPath)) {
    fs.mkdirSync(newPath, { recursive: true });
  }

  // Move existing screenshots if any exist
  if (fs.existsSync(oldPath)) {
    const files = fs.readdirSync(oldPath);
    for (const file of files) {
      const oldFilePath = path.join(oldPath, file);
      const newFilePath = path.join(newPath, file);
      fs.renameSync(oldFilePath, newFilePath);
    }
  }

  store.store = { ...store.store, storagePath: newPath };
  return true;
});

// Handle getting active window
ipcMain.handle('get-active-window', async () => {
  try {
    const result = await activeWin.activeWindow();
    return result ? {
      title: result.title,
      owner: {
        name: result.owner.name,
        path: result.owner.path
      }
    } : null;
  } catch (error) {
    console.error('Error getting active window:', error);
    return null;
  }
});

// Handle getting recent screenshots
ipcMain.handle('get-recent-screenshots', async () => {
  try {
    const storagePath = store.store.storagePath;
    if (!fs.existsSync(storagePath)) {
      return [];
    }

    const files = await fs.promises.readdir(storagePath);
    const screenshots = await Promise.all(
      files
        .filter(file => file.endsWith('.png'))
        .map(async file => {
          const filePath = path.join(storagePath, file);
          const stats = await fs.promises.stat(filePath);
          
          // Try to read metadata if it exists
          let metadata: { id?: string; timestamp?: number; name?: string; activeWindow?: { title: string; app: string } } = {};
          const metaPath = filePath.replace('.png', '.json');
          if (fs.existsSync(metaPath)) {
            try {
              const metaContent = await fs.promises.readFile(metaPath, 'utf-8');
              metadata = JSON.parse(metaContent);
            } catch (error) {
              console.error('Error reading metadata for', file, error);
            }
          }

          // If no metadata file exists, create basic metadata
          if (!Object.keys(metadata).length) {
            metadata = {
              id: file.replace('.png', ''),
              timestamp: stats.mtime.getTime(),
              name: file
            };
            // Save this basic metadata for future use
            try {
              await fs.promises.writeFile(metaPath, JSON.stringify(metadata, null, 2));
            } catch (error) {
              console.error('Error saving basic metadata for', file, error);
            }
          }

          // Generate thumbnail from the image
          let thumbnail: string | undefined;
          let data: string | undefined;
          try {
            const imageBuffer = await fs.promises.readFile(filePath);
            const nativeImage = require('electron').nativeImage;
            const image = nativeImage.createFromBuffer(imageBuffer);
            
            // Set the full image data
            data = imageBuffer.toString('base64');
            
            // Create a thumbnail that's 400px wide (maintaining aspect ratio)
            const size = image.getSize();
            const scaleFactor = 400 / size.width;
            const thumbnailImage = image.resize({
              width: 400,
              height: Math.round(size.height * scaleFactor),
              quality: 'good'
            });
            thumbnail = thumbnailImage.toDataURL().split(',')[1]; // Remove the data:image/png;base64, prefix
          } catch (error) {
            console.error('Error generating thumbnail for', file, error);
          }

          return {
            id: metadata.id || file.replace('.png', ''),
            path: filePath,
            name: metadata.name || file,
            timestamp: metadata.timestamp || stats.mtime.getTime(),
            thumbnail,
            data,
            metadata
          };
        })
    );

    // Sort by timestamp, most recent first
    return screenshots.sort((a, b) => b.timestamp - a.timestamp);
  } catch (error) {
    console.error('Error getting recent screenshots:', error);
    return [];
  }
});

// Handle opening files with system default application
ipcMain.handle('open-file', async (event, filePath) => {
  try {
    await shell.openPath(filePath);
    return true;
  } catch (error) {
    console.error('Error opening file:', error);
    return false;
  }
});

// Register global shortcut
const registerGlobalShortcut = () => {
  const settings = store.store;
  const { shortcut } = settings;
  
  // Unregister any existing shortcuts first
  globalShortcut.unregisterAll();
  
  // Build the accelerator string
  const accelerator = [
    shortcut.ctrl ? 'CommandOrControl' : '',
    shortcut.shift ? 'Shift' : '',
    shortcut.alt ? 'Alt' : '',
    shortcut.key
  ].filter(Boolean).join('+');
  
  try {
    globalShortcut.register(accelerator, async () => {
      const mainWindow = BrowserWindow.getAllWindows()[0];
      if (!mainWindow) return;
      
      try {
        // Get active window information first
        const activeWindow = await activeWin.activeWindow();
        
        // Then capture the screenshot
        const base64Data = await desktopCapturer.getSources({
          types: ['screen'],
          thumbnailSize: screen.getPrimaryDisplay().bounds
        }).then(sources => sources[0]?.thumbnail?.toPNG().toString('base64'));
        
        if (!base64Data) {
          console.error('Failed to capture screenshot in shortcut handler');
          return;
        }
        
        // Get settings here to avoid scoping issues
        const currentSettings = store.store;
        
        // Create screenshot metadata
        const timestamp = Date.now();
        const id = `screenshot_${timestamp}`;
        const filePath = path.join(currentSettings.storagePath, `${id}.png`);
        const metaPath = filePath.replace('.png', '.json');
        
        const metadata = {
          id,
          timestamp,
          name: path.basename(filePath),
          source: 'shortcut',
          category: 'manual',
          activeWindow: activeWindow ? {
            title: activeWindow.title,
            app: activeWindow.owner.name,
            path: activeWindow.owner.path
          } : undefined
        };

        // Save the screenshot and get the data
        const screenshotData = await handleScreenshotSave(null, {
          screenshot: base64Data,
          savePath: filePath,
          metaPath,
          metadata
        });

        return screenshotData;
      } catch (error) {
        console.error('Error taking screenshot via shortcut:', error);
      }
    });
  } catch (error) {
    console.error('Error registering global shortcut:', error);
  }
};

// Handle screenshot deletion
ipcMain.handle('delete-screenshot', async (event, filePath) => {
  try {
    // Delete the screenshot file
    await fs.promises.unlink(filePath);
    
    // Delete the metadata file if it exists
    const metaPath = filePath.replace('.png', '.json');
    if (fs.existsSync(metaPath)) {
      await fs.promises.unlink(metaPath);
    }
    
    return true;
  } catch (error) {
    console.error('Error deleting screenshot:', error);
    return false;
  }
});

// Handle generating pre-signed URL for S3 upload
ipcMain.handle('generate-presigned-url', async (event, { fileName }) => {
  try {
    const { data, error } = await supabase
      .storage
      .from('screenshots')
      .createSignedUploadUrl(fileName); // Changed to createSignedUploadUrl

    if (error) {
      console.error('Error generating presigned URL:', error);
      throw error;
    }

    if (!data?.signedUrl) {
      console.error('No signed URL in response');
      throw new Error('Failed to generate presigned URL');
    }

    return { data: data.signedUrl };
  } catch (error) {
    console.error('Error generating pre-signed URL:', error);
    return { error: error instanceof Error ? error.message : 'Unknown error occurred' };
  }
});

// Handle creating screenshot record
ipcMain.handle('create-screenshot', async (event, { storage_path, resolution, app_name, metadata }) => {
  try {
    if (!currentSession) {
      console.error('No authenticated session found');
      return { error: 'Authentication required' };
    }

    const { data, error } = await supabase.rpc('create_screenshot', {
      p_storage_path: storage_path,
      p_resolution: resolution,
      p_app_name: app_name,
      p_metadata: metadata,
      p_user_id: currentSession.user.id
    });

    if (error) throw error;
    return { data };
  } catch (error) {
    console.error('Error creating screenshot record:', error);
    return { error: error instanceof Error ? error.message : 'Unknown error occurred' };
  }
});

// Add auth sync handler
let currentSession: Session | null = null;

ipcMain.handle('sync-auth-session', async (event, session) => {
  currentSession = session;
  return { success: true };
});

// Update create-flow handler to use synced session
ipcMain.handle('create-flow', async (event, { name, app_id, resolution, flow_type, is_published }) => {
  try {
    if (!currentSession) {
      console.error('No authenticated session found');
      return { error: 'Authentication required' };
    }

    const { data, error } = await supabase.rpc('create_flow', {
      p_name: name,
      p_app_id: app_id,
      p_resolution: resolution,
      p_flow_type: flow_type,
      p_is_published: is_published,
      p_user_id: currentSession.user.id
    });

    if (error) {
      console.error('Error from create_flow RPC:', error);
      return { error: error.message };
    }

    if (!data || !Array.isArray(data) || data.length === 0) {
      console.error('Invalid response from create_flow RPC:', data);
      return { error: 'Invalid response from server' };
    }

    // Extract the flow from the array and check for error
    const flow = data[0];
    if (flow.error) {
      console.error('Error in flow response:', flow.error);
      return { error: flow.error };
    }

    // Check for valid flow data
    if (!flow.id) {
      console.error('Flow response missing ID:', flow);
      return { error: 'Flow response missing ID' };
    }

    return { data: flow };
  } catch (error) {
    console.error('Error creating flow record:', error);
    return { error: error instanceof Error ? error.message : 'Unknown error occurred' };
  }
});

// Handle creating flow step record
ipcMain.handle('create-flow-step', async (event, step) => {
  try {
    const { data, error } = await supabase.rpc('create_flow_step', {
      p_flow_id: step.flow_id,
      p_name: step.name,
      p_description: step.description,
      p_screenshot_id: step.screenshot_id,
      p_order_index: step.order_index,
      p_metadata: step.metadata
    });

    if (error) throw error;
    return { data };
  } catch (error) {
    console.error('Error creating flow step record:', error);
    return { error: error instanceof Error ? error.message : 'Unknown error occurred' };
  }
});

// Handle getting apps list
ipcMain.handle('get-apps', async () => {
  try {
    const { data, error } = await supabase
      .rpc('get_apps_list');

    if (error) throw error;
    // Ensure we always return an array
    const apps = Array.isArray(data) ? data : [];
    return { data: apps };
  } catch (error) {
    console.error('Error getting apps:', error);
    return { data: [], error: error instanceof Error ? error.message : 'Unknown error occurred' };
  }
});

// Add this with other ipcMain handlers
ipcMain.handle('show-error-dialog', async (event, { title, message }) => {
  const { dialog } = require('electron');
  await dialog.showErrorBox(title, message);
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

